import {StyleSheet} from 'react-native';
import {white} from '../../../assets/colors/index';

const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: white,
    flex: 1,
  },
  backButton: {
    width: '100%',
    height: 40,
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  profileInfoContainer: {
    flexDirection: 'row',
    height: 200,
    width: '100%',
    padding: 10,
    alignItems: 'center',
    borderColor: '#fff',
    borderBottomColor: '#0149AF',
    borderWidth: 1.5,
    borderBottomStartRadius: 20,
    borderBottomEndRadius: 20,
  },
  profileImage: {
    width: 110,
    height: 110,
    marginRight: 15,
    borderRadius: 60,
    borderWidth: 2,
  },
  username: {
    color: '#111',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    alignSelf: 'flex-start',
  },
  userInteractions: {alignItems: 'center', paddingRight: 5},
  userInteractionsText: {
    color: '#111',
    fontSize: 12,
  },
  followButton: {
    backgroundColor: '#0149AF',
    borderRadius: 20,
    height: 30,
    width: 120,
    justifyContent: 'center',
    alignItems: 'center',
  },
  followText: {color: '#fff', fontSize: 18, fontWeight: 'bold'},
  imagesGroup: {
    width: '100%',
    flexWrap: 'wrap',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingLeft: 10,
  },
  itemContainer: {
    marginRight: 10,
    marginBottom: 15,
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: 130,
    width: '30%',
    height: 130 * 1.3,
    shadowColor: '#000',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 1.84,
    elevation: 3,
  },
  itemView: {
    width: '100%',
    height: '100%',
    minWidth: 120,
    minHeight: 120 * 1.3,
  },
  itemPhoto: {
    width: '100%',
    height: '100%',
    resizeMode: 'stretch',
    borderRadius: 15,
  },

  trendTitleView: {
    backgroundColor: '#0149AF',
    opacity: 0.7,
    position: 'absolute',
    bottom: 0,
    right: 0,
    left: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
    borderBottomEndRadius: 5,
    borderBottomStartRadius: 5,
  },
  trendTitleText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  searchBar: {
    borderRadius: 25,
    borderColor: '#999',
    borderWidth: 1,
    width: '60%',
    minHeight: 40,
    maxHeight: 50,
    alignSelf: 'center',
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 10,
  },
  searchText: {
    color: '#999',
    fontSize: 19,
    textAlign: 'center',
    width: '82%',
  },
});

export default styles;
